artifact_location: file:///c:/Users/karol/OneDrive/Bureaublad/HHS/Jaar 2 Semester
  4/Deep Learning/Deep-Learning-Portfolio-3/runs/mlflow/564632388259091235
creation_time: 1751640858680
experiment_id: '564632388259091235'
last_update_time: 1751640858680
lifecycle_stage: active
name: /Shared/Ultralytics
